---
title: "codebook"
author: "Morgan Weaver"
date: "8/16/2020"
output: word_document
---

Variables in this dataset include

Subject
     column labled 1 to 30 for each subject in the trial

Activity
     Activity being done by subject as listed below
          WALKING
          WALKING_UPSTAIRS
          WALKING_DOWNSTAIRS
          SITTING
          STANDING
          LAYING

Movement Labels
     Labels that indicate the type of movement done in a given moment by
     participant by activity label as listed below
          "activitylabel"
          "subject"
          "tBodyAcc-mean()-X"
          "tBodyAcc-mean()-Y"
          "tBodyAcc-mean()-Z"
          "tBodyAcc-std()-X"
          "tBodyAcc-std()-Y"
          "tBodyAcc-std()-Z"
          "tGravityAcc-mean()-X"
          "tGravityAcc-mean()-Y"
          "tGravityAcc-mean()-Z"
          "tGravityAcc-std()-X"
          "tGravityAcc-std()-Y"
          "tGravityAcc-std()-Z"
          "tBodyAccJerk-mean()-X"
          "tBodyAccJerk-mean()-Y"
          "tBodyAccJerk-mean()-Z"
          "tBodyAccJerk-std()-X"
          "tBodyAccJerk-std()-Y"
          "tBodyAccJerk-std()-Z"
          "tBodyGyro-mean()-X"
          "tBodyGyro-mean()-Y"
          "tBodyGyro-mean()-Z"
          "tBodyGyro-std()-X"
          "tBodyGyro-std()-Y"
          "tBodyGyro-std()-Z"
          "tBodyGyroJerk-mean()-X"
          "tBodyGyroJerk-mean()-Y"
          "tBodyGyroJerk-mean()-Z"
          "tBodyGyroJerk-std()-X"
          "tBodyGyroJerk-std()-Y"
          "tBodyGyroJerk-std()-Z"
          "tBodyAccMag-mean()"
          "tBodyAccMag-std()"
          "tGravityAccMag-mean()"
          "tGravityAccMag-std()"
          "tBodyAccJerkMag-mean()"
          "tBodyAccJerkMag-std()"
          "tBodyGyroMag-mean()"
          "tBodyGyroMag-std()"
          "tBodyGyroJerkMag-mean()"
          "tBodyGyroJerkMag-std()"
          "fBodyAcc-mean()-X"
          "fBodyAcc-mean()-Y"
          "fBodyAcc-mean()-Z"
          "fBodyAcc-std()-X"
          "fBodyAcc-std()-Y"
          "fBodyAcc-std()-Z"
          "fBodyAccJerk-mean()-X"
          "fBodyAccJerk-mean()-Y"
          "fBodyAccJerk-mean()-Z"
          "fBodyAccJerk-std()-X"
          "fBodyAccJerk-std()-Y"
          "fBodyAccJerk-std()-Z"
          "fBodyGyro-mean()-X"
          "fBodyGyro-mean()-Y"
          "fBodyGyro-mean()-Z"
          "fBodyGyro-std()-X"
          "fBodyGyro-std()-Y"
          "fBodyGyro-std()-Z"
          "fBodyAccMag-mean()"
          "fBodyAccMag-std()"
          "fBodyBodyAccJerkMag-mean()"
          "fBodyBodyAccJerkMag-std()"
          "fBodyBodyGyroMag-mean()"
          "fBodyBodyGyroMag-std()"
          "fBodyBodyGyroJerkMag-mean()"
          "fBodyBodyGyroJerkMag-std()"
     
